url: "https://www.jonathanbaker.me"

title: Jonathan Baker

description: >-
  iOS, Android, and Web Developer

exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
